### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Creeperface01** [PEMapModder/DecMcpe#3]
Line 350457: Reading SetEntityDataPacket packet structure...  1483e6:   ffff e130   vsra.u32    d30, d16, #1
PHP Fatal error:  Uncaught InvalidArgumentException: Not an instruction in /home/honza/DMCPE/Instruction.php:46
Stack trace:
#0 /home/honza/DMCPE/Packet.php(53): Instruction->__construct('  1483e6:\tffff ...')
#1 /home/honza/DMCPE/_DecPacket.php(76): Packet->analyze('  1483e6:\tffff ...')
#2 {main}

  thrown in /home/honza/DMCPE/Instruction.php on line 46

**Comment by Creeperface01** [comment]
I tried to decompile 0.14.0

**Comment by PEMapModder** [comment]
Yes, I know that the HEAD is having bugs.
